### ISSUE TITLE
Dumping non-ASCII bytes produces gibberish

### ISSUE THREAD

**Issue by Julian** [uiri/toml#144]
```
>>> import toml; print toml.dumps({'username': 'שלום'})
username = "\u00d7\u00a9\u00d7\u009c\u00d7\u0095\u00d7\u009d"
```

where that value (which you can get back again via loads obviously) is `u'\xd7\xa9\xd7\x9c\xd7\x95\xd7\x9d'` which is very different from `'\xd7\xa9\xd7\x9c\xd7\x95\xd7\x9d'` (the bytes, which are what was sent in), and which as unicode are u'\u05e9\u05dc\u05d5\u05dd'.

There should really be only 2 ways to treat passing in bytes there, either it should assume some encoding ([which is what the `json` module does, and allows you to override which encoding](https://docs.python.org/2/library/json.html#json.dump)) or it should just raise an exception and always ask users to provide unicode objects.

**Comment by uiri** [comment]
Per [the spec](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md#spec), TOML is UTF-8 encoded. I'm not really sure what the bug is here since the data you get back is the same as the data which you put in.

Are you expecting the library to arbitrarily transcode non-unicode strings to unicode?

**Comment by Julian** [comment]
That's the encoding of the output file -- not the encoding of bytes handed to the library to serialize into TOML, those may or may not even be valid UTF-8. Though yeah if you say "only accept UTF-8 bytes", and then not add an encoding argument (and just force anyone with non-UTF-8 bytes to manually decode them) that might be reasonable (though it's not that easy to manually decode random arbitrarily nested bytes in some structured object)

The point though is exactly that the data is *not* the same as what was put in. u'\xd7\xa9\xd7\x9c\xd7\x95\xd7\x9d' is very different from '\xd7\xa9\xd7\x9c\xd7\x95\xd7\x9d', and u'\xd7\xa9\xd7\x9c\xd7\x95\xd7\x9d'.encode("utf-8") is very much not '\xd7\xa9\xd7\x9c\xd7\x95\xd7\x9d'.

Put more simply:

```
>>> import toml; print toml.loads(toml.dumps({'username': 'שלום'}))["username"]
×©×××
```

which is not the bytes that were fed in.

It's the `_dump_str` function that looks like it's doing that (and looks very suspicious overall to me).

> Are you expecting the library to arbitrarily transcode non-unicode strings to unicode?

It already does that :), it just decodes them into stuff that isn't the UTF-8 decoded version of the bytes given.

**Comment by uiri** [comment]
OK, so you have a unicode string inside of a regular/byte string which is then interpreted as the raw UTF-8 bytes instead of the Unicode hex points that those bytes represent. That's definitely a bug but it strikes me as one which may be difficult to fix. I am a little wary of messing with the decoding/encoding logic too much because it has gone through a handful of iterations already (I think).

Why isn't it already a unicode string if that is its encoding?  
If you receive it that way (e.g. user input of some sort), have you tried running `s.decode('utf-8')` before feeding it into TOML?  
Is this an issue in Python3 too or only in Python2?

**Comment by Julian** [comment]
> Why isn't it already a unicode string if that is its encoding?

Because in Py2, a str is an equally reasonable way to pass text around :), but also because of what I mentioned about it not being too convenient to go decode all the string keys of a big nested object.

Because of this bug though that's exactly what I'm doing though, yes, and yes passing unicode objects into TOML does the correct thing.

> Is this an issue in Python3 too or only in Python2?

Haven't checked for sure, but from reading that code, almost certainly.

I can have a look at a PR if I get a minute here.

**Comment by jamessa** [comment]
@Julian  you're right, by trim out the _dump_str, my unicode worked.
```
def _dump_str(v):
    return v
```
