### ISSUE TITLE
Copy toml.pyi to typeshed, or install it per PEP 561?

### ISSUE THREAD

**Issue by gvanrossum** [uiri/toml#178]
I notice there's no types stub for toml in https://github.com/python/typeshed nor does it look like you have got a py.typed marker file (see PEP 561). The simplest thing might be to copy toml.pyi into typeshed. Are you okay with that? Alternatively, do you want to follow PEP 561?

CC: @ethanhs (he can explain what needs to be done for PEP 561 -- there are a few options).

**Comment by uiri** [comment]
Thank you for opening this issue! Yes, I am OK with having a copy of toml.pyi in the typeshed package.

Type information is not something I have thought very much about since this package is intended to target both python2 and python3. Of course, there is no harm in having `*.pyi` files or a `py.typed` file.

**Comment by gvanrossum** [comment]
Thanks! I'll see if your toml.pyi can be copied into typeshed/third_party/2and3/.

**Comment by uiri** [comment]
Closing this as it appears that the pyi file has been copied into typeshed.

Thanks!
