### ISSUE TITLE
group name character constraints

### ISSUE THREAD

**Issue by cckuailong** [uiri/toml#290]
First, Thank you for the excellent toml paser.
I have a problem here
When I parse the toml
```
[测试]
url = "test"
```
I got an error: 
toml.decoder.TomlDecodeError: Invalid group name '测试'. Try quoting it.

I read the decoder.py, I find the constraints of the group name here
```
_groupname_re = re.compile(r'^[A-Za-z0-9_-]+$')
```
I don't know why constraints here. If I modify it to 
```
_groupname_re = re.compile(r'^.*?$')
```
Everything is ok. 

So, is it a bug or the special design.

**Comment by eksortso** [comment]
As of v0.5 of the TOML standard, which the `toml` module conforms to: bare keys, like unquoted table names, "[may only contain ASCII letters, ASCII digits, underscores, and dashes](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md#user-content-keys)," so what you're seeing is intentional behavior. It's not special; it's standard.

So, like the error message said, try quoting it. `toml` does parse this:
```toml
["测试"]
url = "test"
```

There is [action being taken in the standard](https://github.com/toml-lang/toml/issues/687) to allow more Unicode characters in bare keys, including Chinese text. But that will take some time.

**Comment by cckuailong** [comment]
Thank u for reply, I didn't see the standard of toml before. Thank u
