### ISSUE TITLE
Cannot dump an array with a dictionary

### ISSUE THREAD

**Issue by James-Hudson3010** [uiri/toml#320]
I have:

asPython = [ { 'a': 'b' } ]
asTOML = toml.dumps( asPython )

and this produces the error:

`TypeError: list indices must be integers or slices, not str`

It seems like this should work. Or, have I misunderstood something?

**Comment by eksortso** [comment]
Actually, the TOML standard doesn't permit the top level to be anything but a table. `asPython` is a list, so this can't be dumped as  TOML as it is currently defined. A different error message would be in order then.

**Comment by James-Hudson3010** [comment]
interesting. Perhaps consideration can be given to allowing the top level to be a list.

**Comment by eksortso** [comment]
You could take it up at [toml-lang/toml](https://github.com/toml-lang/toml). That project is the TOML standard, and once version 1.0 comes out, it would raise some debate, since allowing top-level arrays goes beyond the configuration standard's primary mission.

As far as this library goes, the error that it throws must acknowledge that as of now, only dicts (are similar mapping types ever used?) are the only top-level objects permitted.
