### ISSUE TITLE
Multiline string passed as value for TOML key loads as a single line string

### ISSUE THREAD

**Issue by TheTravellingSalesman** [uiri/toml#340]
I'm trying to load from a string that contains a multiline string as a value for a TOML key.

Example:

```
toml_string = """
        text = '''Example multiline string with "quotation marks" in it, both 'single' and "double".'''
    """

parsed_toml = toml.loads(toml_string)

print(parsed_toml)
>>> {'text': 'Example multiline string with "quotation marks" in it, both \'single\' and "double".'}
```

The `text` value is stored as a single line string, when it was passed as a multi-line string, which is causing a `TomlDecodeError` when the value spans multiple lines and contains quotation marks or apostrophes. 

What I would expect as output would be:

```
print(parsed_toml)
>>> {'text': '''Example multiline string with "quotation marks" in it, both \'single\' and "double".'''}
```

**Comment by eksortso** [comment]
After parsing the TOML, you have a Python dict where the string `text` is mapped to exactly the string that you provided. That value is a Python string, that is expected behavior, and it no longer possesses the string type that TOML used in its syntax.

In your expected result, you don't want the single quotes to be recaped within the Python multi-line string. Single-quotes are used between triple-single quotes without backslashes.

**Comment by uiri** [comment]
Thank you for reporting this issue and thank you @eksortso for explaining how this is expected behaviour.
