### ISSUE TITLE
Option to load many config files

### ISSUE THREAD

**Issue by matrixik** [uiri/toml#9]
I like from Python ConfigParser option to load many config files:

``` python
from ConfigParser import SafeConfigParser

parser = SafeConfigParser()

parser.read(['does_not_exist.ini', 'config.ini', 'config_dev.ini', ])

print 'Log level:', parser.get('logging', 'log_level')
print 'Prefix:', parser.get('logging', 'prefix')
```

if `'config.ini`:

``` ini
[logging]
log_level = info
prefix = 'my_prefix'
```

and `config_dev.ini`:

``` ini
[logging]
log_level = debug
```

Output would be:

```
Log level: debug
Prefix: "my_prefix"
```

If I remove `config_dev.ini`, output will be:

```
Log level: info
Prefix: "my_prefix"
```

> ConfigParser overwrites the keys with each successive file, the order in which the files are read is determined by the order of the file names in the list passed to ConfigParser.read

Docs: http://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.read

If files not exists instead of throwing error:

> If none of the named files exist, the ConfigParser instance will contain an empty dataset.

From http://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.read

Would be nice if you could add something similar.

Best regards,
Dobrosław Żybort

P.S. Now, to merge multi-level dicts, I need to use http://stackoverflow.com/a/10704003/1722542

**Comment by machielg** [comment]
Could this be a regression? I don't see any reference to the fix for this issue in the current code. It looks like the [current version](https://github.com/uiri/toml/blob/230f0c9cffd230354759949dd1dd89acd3dddb80/toml/decoder.py#L149) uses the python update which breaks the initially requested behaviour. At least in my own code I see a simple key overwriting happening in v0.10.2

**Comment by PMeira** [comment]
@machielg I was curious about this but couldn't find any explanation why it was removed besides the commit message from ca3d32e574f85e364d104117af0a6c7fa667910d, from 2016.

Unless I missed a note somewhere, maybe a note about this incomplete merge behavior could be added, especially since the module did use a different merge strategy in the past.

**Comment by machielg** [comment]
Can we reopen this issue? Or a new one?
