### ISSUE TITLE
Update pypa version - Release 0.9.3

### ISSUE THREAD

**Issue by samvasko** [uiri/toml#90]
The version seems to be quite old
```
Name: toml
Version: 0.9.2
```

**Comment by uiri** [comment]
Hi Sam,

The last release was around the end of last July. Most of the development activity since then has been over the past couple of months. I plan on doing a new release once I resolve the currently open bugs.

**Comment by samvasko** [comment]
I think the release cycle must be shorter than one year. I am having to use a git version  because of bug I fixed on Jan 2, 2017. Does it involve anything more than creating a tag and updating a file?

**Comment by jakory** [comment]
Are there plans to do a new release soon?

For a single user, it's straightforward enough to check out master from git to get the bug fixes from the past year, but it would be very useful to be able to tell the other people I work with to simply `pip install toml` to get the latest version.

**Comment by uiri** [comment]
@samvasko Do you want to make the new release? I think that the current outstanding issues will take some time to resolve so doing a release sooner rather than later would be wise. I am putting together a small RELEASE.rst document to help.

I believe the following Copyright notices need to be added to the LICENSE file (unless those named - @samvasko, @nateprewitt, @Jackevansevo - object to their inclusion):

```
Copyright 2017 Samuel Vasko
Copyright 2017 Nate Prewitt
Copyright 2017 Jack Evans
```

**Comment by nateprewitt** [comment]
Sorry for the delayed response. No issues on my end. Congrats on the new release 🎉

**Comment by Woile** [comment]
Hi guys, I'd like to know when will the next version be released.

Thanks!
